# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
port: 4000
highlighter: pygments
title: Toxiclibs gem for JRubyArt
email: mamba2928@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  A gem wrapper for the awesome toxilibs library, that you can now easily 
  use with JRubyArt 
baseurl: "/toxicgem" # the subpath of your site, e.g. /blog
url: "http://ruby-processing.github.io/toxicgem" # the base hostname & protocol for your site
twitter_username: monkstoneT
github_username:  monkstone

syntax-highlighting:
  enabled: true
  css: syntax.css        
# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap

