# Site settings
port: 4000
title: Toxiclibs gem for JRubyArt
email: mamba2928@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  A gem wrapper for the awesome toxiclibs library, that you can now easily
  use with JRubyArt / propane
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://ruby-processing.github.io/toxicgem"
urls:
  bugs: http://github.com/ruby-processing/toxicgem/issues
  github: http://github.com/ruby-processing/toxicgem/
twitter_username: monkstoneT
github_username:  monkstone

syntax-highlighting:
  enabled: true
# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
